typography_spectrum: 0.296867814283486
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.3038881612789476
  lightness: 0.4766390221541987
  saturation: 0.8487074135236515
  rhythmicContrast: 0.5201317984401479
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.18117761160864834
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Paul-Louis Pröve
  email: mail@plpp.de
name: Paul-Louis Pröve
url: 'http://plpp.de'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: GitHub
    url: 'https://github.com/pietz'
    type: external
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/pietzprove/'
    type: external
  - name: Xing
    url: 'https://www.xing.com/profile/PaulLouis_Proeve'
    type: external
  - name: Medium
    url: 'https://medium.com/@pietz'
    type: external
favicon: null
title: Paul-Louis Pröve
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FhxzalPzcSgA%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DhxzalPzcSgA&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FhxzalPzcSgA%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Paul-Louis Pietz Pröve
          url: 'https://www.youtube.com/channel/UCH1QARsV9pnOacNuaFtt0Xg'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - ''
      description: Snippet of a VR Game I'm wokring on
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=hxzalPzcSgA&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=hxzalPzcSgA&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=hxzalPzcSgA&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=hxzalPzcSgA&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=hxzalPzcSgA&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=hxzalPzcSgA'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=hxzalPzcSgA
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=hxzalPzcSgA
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/hxzalPzcSgA'
      title: VRUN Teaser
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: computer scientist specialising in artificial intelligence
purpose: []
