typography_spectrum: 0.296867814283486
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.3038881612789476
  lightness: 0.4766390221541987
  saturation: 0.8487074135236515
  rhythmicContrast: 0.5201317984401479
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.18117761160864834
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Paul-Louis Pröve
  email: mail@plpp.de
name: Paul-Louis Pröve
url: 'http://plpp.de'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: GitHub
    url: 'https://github.com/pietz'
    type: external
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/pietzprove/'
    type: external
  - name: Medium
    url: 'https://medium.com/@pietz'
    type: external
  - name: Xing
    url: 'https://www.xing.com/profile/PaulLouis_Proeve'
    type: external
favicon: null
title: Paul-Louis Pröve
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/e38cd300-70ea-449b-b976-2ced9c71bdcd.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/e38cd300-70ea-449b-b976-2ced9c71bdcd.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: computer scientist specialising in artificial intelligence
purpose: []
